#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
export EDITOR=nvim
export VISUAL=nvim
PS1='[\u@\h \W]\$ '
# Wallpaper-driven prompt colors (generated by ~/bin/wallpaper-theme); falls back to ~/.config/starship.toml.
[ -f "$HOME/.cache/wallpaper-theme/starship.toml" ] && export STARSHIP_CONFIG="$HOME/.cache/wallpaper-theme/starship.toml"
eval "$(starship init bash)"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

# Created by `pipx` on 2026-07-18 23:39:18
export PATH="$PATH:/home/mythra/.local/bin"
