-- Generated by matugen (wallpaper-theme). Do not edit; edit the template in
-- ~/dotfiles/matugen/.config/matugen/templates/hypr-colors.lua instead.
return {
    active   = "rgba({{colors.primary.default.hex_stripped}}ee)",
    inactive = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",
}
