[addressbooks]
[[contacts]]
path = ~/.local/share/contacts/allcontacts/

[general]
default_action = list
editor = nvim
merge_editor = nvim -d

[contact table]
display = formatted_name
sort = last_name
show_nicknames = no
show_uids = no
preferred_phone_number_type = pref, cell, home
preferred_email_address_type = pref, work, home

[vcard]
preferred_version = 3.0
search_in_source_files = no
skip_unparsable = no
