general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 320, 60
    outline_thickness = 2

    inner_color = rgba(20, 20, 20, 0.85)
    outer_color = rgba(51, 204, 255, 1.0)
    font_color = rgba(235, 219, 178, 1.0)

    placeholder_text = <i>Password...</i>

    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(235, 219, 178, 1.0)
    font_size = 64

    position = 0, 100
    halign = center
    valign = center
}
