# Automatically copy highlighted text
copy_on_select clipboard

# Copy and paste shortcuts
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
include gruvbox-teal.conf


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS